### ISSUE TITLE
kotlin-stdlib incorrect version when upgrading to 0.19.0

### ISSUE THREAD

**Issue by paul-dingemans** [drewhamilton/Poko#557]
Tnx for upgrading `poko-gradle-plugin` to Kotlin `2.2.0`. Unfortunately, this upgrade fails in [ktlint](https://github.com/pinterest/ktlint/actions/runs/16006512333/job/45154347668?pr=3024#step:4:32) with following compilation errors:
```
> Task :build-logic:compilePluginsBlocks FAILED
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/dev.drewhamilton.poko/poko-gradle-plugin/0.19.0/854ca0e02eeb7f36337a8b7c34b2e38b0dbcd9d4/poko-gradle-plugin-0.19.0.jar!/META-INF/poko-gradle-plugin.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca[33](https://github.com/pinterest/ktlint/actions/runs/16006512333/job/45154347668?pr=3024#step:4:34)5fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.```

Ktlint has been uograded to Kotlin `2.2.0`. 

Do you any idea how to resolve? Ktlint still works with older version, so I have no immediate need to get this resolved.

**Comment by drewhamilton** [comment]
I notice that the error is in the `:build-logic` module. I wonder whether this module is compiled with Gradle's embedded Kotlin version, 2.0.21, and whether that is the source of the mismatch.

I confirmed that Poko depends on 2.2.0 as expected, based on [this POM file](https://central.sonatype.com/artifact/dev.drewhamilton.poko/poko-gradle-plugin), so I'm closing this. But feel free to reopen if you do trace it back to Poko again.

**Comment by 3flex** [comment]
@drewhamilton I believe this should be reopened. The Gradle plugin should not be built with version of Kotlin that's too far ahead of what Gradle embeds, otherwise workarounds are required. Instead the plugin should be made compatible with production versions of Gradle.

We faced this with detekt as well, see https://github.com/detekt/detekt/pull/7798

I'm happy to open a PR if you're open to this.

**Comment by drewhamilton** [comment]
According to [this](https://kotlinlang.org/docs/build-tools-api.html#limitations), it may cause problems with compiler plugins. But maybe that's only if it's applied directly in the compiler plugin module? If it works for you then it's worth a try.

**Comment by 3flex** [comment]
>  the Gradle plugin should set apiVersion and languageVersion but still use the latest compiler

Yes, I think that's right. The reason detekt used the build tools API with an older compiler version is so we could use an API version that was no longer supported in the latest Kotlin release and support quite old Gradle versions.

If Poko will only support recent Gradle versions then that shouldn't be a problem and just setting an older language and API version should be enough.

I'm happy to take this on as it's blocking a couple of things for me.

**Comment by 3flex** [comment]
I've confirmed the snapshot works.
