### ISSUE TITLE
Incompatible with Kotlin 2.0.0-Beta2

### ISSUE THREAD

**Issue by 3flex** [drewhamilton/Poko#278]
Consuming build fails on `compileKotlin` task with error `e: java.lang.IncompatibleClassChangeError: class dev.drewhamilton.poko.ir.PokoOrigin cannot inherit from final class org.jetbrains.kotlin.ir.declarations.IrDeclarationOriginImpl`

Caused by this change: https://github.com/JetBrains/kotlin/commit/a3b55cf758f3a7ceb596f65507c2f61ada5266af

I didn't see a simple backwards-compatible fix but didn't spend much time on it.

**Comment by drewhamilton** [comment]
Thanks for the heads up. Looks like I can implement the interface without too much extra work. Need to wait for a KSP beta to test it.

**Comment by 3flex** [comment]
New KSP is out so I tried making the changes to Poko. The interface change looked simple (see above commit) but I had trouble here:

https://github.com/drewhamilton/Poko/blob/b317fcfc31e4ba4bc289bdd87f61e4a71e45ffcb/poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/ir/hashCodeGeneration.kt#L78

The change to Kotlin appears to be binary incompatible so I can't compile Poko with 1.9.21 and run on 2.0.0-Beta2 as I get `java.lang.NoClassDefFoundError: org/jetbrains/kotlin/ir/declarations/IrDeclarationOrigin$DEFINED`. I can't see a way to keep Poko backwards compatible with 1.9.21 without creating a separate instances of `IrDeclarationOrigin("DEFINED")` in Poko. If that's not a problem then I'll submit a PR.

**Comment by drewhamilton** [comment]
I don't really expect it to be compatible; many Kotlin bumps aren't, and this is a bigger bump than most.

#258 is tracking the Kotlin 2.0 migration. I've just rebased and pushed that branch. Feel free to open a PR targeting that branch with your changes. I haven't looked into the issue you're describing because I'm traveling today, but I can have a look tomorrow.

**Comment by 3flex** [comment]
My content is moot if backwards compatibility isn't required so there won't be anything else to do since you've reimplemented the interface in the Kotlin 2 branch. I've raised a PR to bump KSP though which should resolve the build failure.

**Comment by 3flex** [comment]
Confirming this issue will be fixed by #258 - I've now used that branch successfully on a build using 2.0.0-Beta2.

**Comment by drewhamilton** [comment]
Once a compatible dev build of Compose lands, we can start publishing snapshots of the 2.0 branch.

**Comment by drewhamilton** [comment]
Snapshot publishing is now enabled on the `drew/kotlin-2.0` branch. `0.16.0-SNAPSHOT` is now built with Kotlin 2.0. `0.15.3-SNAPSHOT` is still built with Kotlin 1.9.
