### PR TITLE
Build Gradle plugin with compatibility with Kotlin 2.1

### LINKED ISSUE #557: kotlin-stdlib incorrect version when upgrading to 0.19.0
Tnx for upgrading `poko-gradle-plugin` to Kotlin `2.2.0`. Unfortunately, this upgrade fails in [ktlint](https://github.com/pinterest/ktlint/actions/runs/16006512333/job/45154347668?pr=3024#step:4:32) with following compilation errors:
```
> Task :build-logic:compilePluginsBlocks FAILED
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/dev.drewhamilton.poko/poko-gradle-plugin/0.19.0/854ca0e02eeb7f36337a8b7c34b2e38b0dbcd9d4/poko-gradle-plugin-0.19.0.jar!/META-INF/poko-gradle-plugin.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca[33](https://github.com/pinterest/ktlint/actions/runs/16006512333/job/45154347668?pr=3024#step:4:34)5fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.
e: file:///home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/2.2.0/fdfc65fbc42fda253a26f61dac3c0aca335fae96/kotlin-stdlib-2.2.0.jar!/META-INF/kotlin-stdlib.kotlin_module Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.2.0, expected version is 2.0.0.```

Ktlint has been uograded to Kotlin `2.2.0`. 

Do you any idea how to resolve? Ktlint still works with older version, so I have no immediate need to get this resolved.

### PR DESCRIPTION
**Pull request by 3flex**
This will ensure compatibility with Gradle 8.11 which embeds Kotlin 2.0.x, which is forward compatible with Kotlin 2.1.

It will also be compatible with all newer Gradle versions that embed Kotlin versions that are backwards-compatible with Kotlin 2.1.

Fixes #557

### CODE REVIEW

**Comment by drewhamilton** [comment]
Thanks!
